# Generated by Django 5.1.15 on 2026-08-16 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_legacy_mcp_activity(apps, schema_editor):
    ApiKeyAuditLog = apps.get_model("api_keys", "ApiKeyAuditLog")
    McpActivityEvent = apps.get_model("mcp_server", "McpActivityEvent")
    OrgMembership = apps.get_model("members", "OrgMembership")

    logs = ApiKeyAuditLog.objects.filter(action__startswith="mcp.").select_related("api_key__workspace")
    for log in logs.iterator(chunk_size=500):
        credential_type = "api_key" if log.api_key_id else "oauth"
        workspace_id = log.api_key.workspace_id if log.api_key_id else None
        organization_id = log.api_key.workspace.organization_id if log.api_key_id else None
        actor_id = log.api_key.issued_by_id if log.api_key_id else log.actor_user_id
        if organization_id is None and actor_id is not None:
            organization_ids = list(
                OrgMembership.objects.filter(user_id=actor_id).values_list("organization_id", flat=True)[:2]
            )
            if len(organization_ids) == 1:
                organization_id = organization_ids[0]
        primitive = "method"
        name = log.action.removeprefix("mcp.")[:128]
        if name.startswith("tools/call:"):
            primitive = "tool"
            name = name.partition(":")[2][:128] or "unknown"
        status = "succeeded" if 200 <= log.status_code < 300 else "failed"
        if log.status_code in {401, 403}:
            status = "denied"
        elif log.status_code == 429:
            status = "rate_limited"
        event = McpActivityEvent.objects.create(
            organization_id=organization_id,
            workspace_id=workspace_id,
            actor_id=actor_id,
            api_key_id=log.api_key_id,
            credential_type=credential_type,
            primitive=primitive,
            name=name,
            status=status,
            duration_ms=0,
            summary={"legacy_audit_id": str(log.id)},
        )
        McpActivityEvent.objects.filter(pk=event.pk).update(created_at=log.created_at)


def reverse_backfill_legacy_mcp_activity(apps, schema_editor):
    McpActivityEvent = apps.get_model("mcp_server", "McpActivityEvent")
    McpActivityEvent.objects.filter(summary__has_key="legacy_audit_id").delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_keys', '0003_apikeyauditlog_actor_label_apikeyauditlog_actor_user_and_more'),
        ('members', '0002_invitation_org_role'),
        ('organizations', '0002_organization_billing_email'),
        ('workspaces', '0003_alter_workspace_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='McpOrganizationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_config', to='organizations.organization')),
            ],
            options={
                'db_table': 'mcp_organization_config',
            },
        ),
        migrations.CreateModel(
            name='McpActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('api_key', 'API key'), ('oauth', 'OAuth')], max_length=16)),
                ('primitive', models.CharField(choices=[('method', 'Method'), ('tool', 'Tool'), ('resource', 'Resource'), ('prompt', 'Prompt')], max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('target_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('denied', 'Denied'), ('rate_limited', 'Rate limited')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('protocol_version', models.CharField(blank=True, default='', max_length=32)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('confirmation_state', models.CharField(choices=[('not_required', 'Not required'), ('preview', 'Preview'), ('confirmed', 'Confirmed'), ('replayed', 'Replayed'), ('rejected', 'Rejected')], default='not_required', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_activity_events', to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_activity_events', to='api_keys.apikey')),
                ('oauth_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mcp_activity_events', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_activity_events', to='organizations.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_activity_events', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mcp_activity_event',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='mcp_activity_org_time'), models.Index(fields=['workspace', 'created_at'], name='mcp_activity_ws_time'), models.Index(fields=['primitive', 'name'], name='mcp_activity_primitive')],
            },
        ),
        migrations.CreateModel(
            name='McpConfirmationGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('api_key', 'API key'), ('oauth', 'OAuth')], max_length=16)),
                ('tool_name', models.CharField(max_length=128)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('safe_preview', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_keys.apikey')),
                ('oauth_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mcp_confirmation_grant',
                'indexes': [models.Index(fields=['workspace', 'tool_name', 'expires_at'], name='mcp_grant_ws_tool_exp')],
            },
        ),
        migrations.CreateModel(
            name='McpIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('api_key', 'API key'), ('oauth', 'OAuth')], max_length=16)),
                ('credential_digest', models.CharField(max_length=64)),
                ('tool_name', models.CharField(max_length=128)),
                ('idempotency_key_digest', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('response_summary', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mcp_idempotency_record',
                'indexes': [models.Index(fields=['created_at'], name='mcp_idem_created_at')],
                'constraints': [models.UniqueConstraint(fields=('credential_digest', 'tool_name', 'idempotency_key_digest'), name='mcp_unique_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='McpToolPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_policies', to='organizations.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_tool_policies', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'mcp_tool_policy',
                'indexes': [models.Index(fields=['tool_name', 'enabled'], name='mcp_policy_tool_enabled')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('workspace__isnull', True)), fields=('organization', 'tool_name'), name='mcp_unique_org_tool_policy'), models.UniqueConstraint(condition=models.Q(('workspace__isnull', False)), fields=('workspace', 'tool_name'), name='mcp_unique_workspace_tool_policy')],
            },
        ),
        migrations.RunPython(backfill_legacy_mcp_activity, reverse_backfill_legacy_mcp_activity),
    ]
